[messages]
no_party = "You don't have a party!"
has_party = "You are already in a party!"
sender_invited_expired = "The invite is expired."
party_invited_joined = "%s joined the party!"
sender_invited_joined = "You joined the party!"
party_chat_message = "§aPARTY §6[%s] >> §7%s"
sender_party_created = "Party created!"
sender_cannot_disband = "You must be the leader!"
party_disbanded = "The party has been disbanded!"
sender_disbanded = "You disbanded the party!"
sender_no_permissions = "You must be leader or mod!"
sender_cannot_self_invited = "You cannot invite yourself!"
sender_invited_player_has_party = "The player is already in a party!"
sender_player_already_invited = "Player invite still pending!"
sender_player_invited = "You have invited %s to joined your party!"
player_invited = "%s invited you to join the party!"
sender_cannot_kick_self = "You can't kick yourself!"
sender_player_not_in_party = "The player is not in the party!"
sender_cannot_kick_mod = "You must be leader to kick a mod!"
sender_cannot_kick_leader = "You can't kick the leader!"
player_kicked = "You have been kicked from the party!"
party_kicked = "%s has been kicked from the party!"
sender_kicked = "You kicked %s from the party!"
sender_cannot_leave_leader = "You are the leader!"
party_player_left = "%s left the party!"
sender_party_left = "You left the party!"
sender_no_permissions_only_leader = "You must be the leader!"
sender_cannot_promote_self = "You can't promote yourself!"
sender_player_not_found = "Player not found!"
sender_party_rank_not_found = "Rank not found!"
sender_player_already_mod = "The player is already a mod!"
player_promoted = "You have been promoted to Party %s!"
party_promoted = "%s has been promoted to Party %s"
sender_promoted = "You have promoted %s to Party %s!"
sender_cannot_demote_leader = "A leader can't be demoted."
sender_player_not_mod = "The player is not a mod!"
player_demoted = "You have been demoted to Party Member!"
party_demoted = "%s has been demoted to Party Member!"
sender_demoted = "You have demoted %s to Party Member!"

sender_party_list_leader = "Party Leader: %s"
sender_party_list_mods = "Party Moderators: %s"
sender_party_list_members = "Party Members: %s"
