[errors]
no_party = "You don't have a party!"
has_party = "You are already in a party!"
cannot_self_invite = "You cannot invite yourself!"
already_invited = "There's still a pending invite!"
expired_invite = "The invite is expired."
invited_player_has_party = "The invited player is already in a party!"

[info]
party_created = "You made a party!"
invited_by = "%s invited you to join the party!"
player_joined = "%s joined the party!"
party_joined = "You joined the party!"
party_disbanded_by = "The party has been disbanded!"
party_disbanded = "You disbanded the party!"
invited = "You have invited %s to joined your party!"
party_left = "You left the party!"
