[errors]
no_party = "You don't have a party!"
has_party = "You are already in a party!"
cannot_self_invite = "You cannot invite yourself!"
already_invited = "There's still a pending invite!"
expired_invite = "The invite is expired."
invited_player_has_party = "The invited player is already in a party!"
cannot_disband_not_leader = "You MUST be the leader to disband!"
cannot_leave_leader = "You are the leader!"
no_permissions = "You must be leader!"
cannot_kick_not_in_party = "The player is not in the party!"

[info]
party_created = "You made a party!"
invited_by = "%s invited you to join the party!"
player_joined = "%s joined the party!"
party_joined = "You joined the party!"
party_disbanded_by = "The party has been disbanded!"
party_disbanded = "You disbanded the party!"
invited = "You have invited %s to joined your party!"
party_left = "You left the party!"
player_left = "%s left the party!"
player_kicked = "%s has been kicked from the party!"
party_kicked = "You have been kicked from the party!"
you_kicked = "You kicked %s from the party!"
party_chat = "§aPARTY §6[%s] >> §7%s"
