[errors]
no_party = "You don't have a party!"
has_party = "You are already in a party!"
cannot_self_invite = "You cannot invite yourself!"
already_invited = "There's still a pending invite!"
expired_invite = "The invite is expired."
invited_player_has_party = "The invited player is already in a party!"
cannot_disband_not_leader = "You MUST be the leader to disband!"
cannot_leave_leader = "You are the leader!"
no_permissions = "You must be leader!"
cannot_kick_not_in_party = "The player is not in the party!"
player_not_found = "Player not found!"
player_already_mod = "The player is already a mod!"
no_permissions_only_leader = "You must be the leader!"
party_rank_not_found = "Rank not found!"
cannot_self_promote = "You can't promote yourself!"
player_not_mod = "The player is not a mod!"
cannot_demote_leader = "A leader can't be demoted."

[info]
party_created = "Party created!"
invited_by = "%s invited you to join the party!"
player_joined = "%s joined the party!"
party_joined = "You joined the party!"
party_disbanded_by = "The party has been disbanded!"
party_disbanded = "You disbanded the party!"
invited = "You have invited %s to joined your party!"
party_left = "You left the party!"
player_left = "%s left the party!"
player_kicked = "%s has been kicked from the party!"
party_kicked = "You have been kicked from the party!"
you_kicked = "You kicked %s from the party!"
party_chat = "§aPARTY §6[%s] >> §7%s"
player_promoted = "You have been promoted to Party %s!"
party_promoted = "%s has been promoted to Party %s"
sender_promoted = "You have promoted %s to Party %s!"
player_demoted = "You have been demoted to Party Member!"
party_demoted = "%s has been demoted to Party Member!"
sender_demoted = "You have demoted %s to Party Member!"
